#!/usr/bin/env python3
"""
Voynich Manuscript Research Program
TEST 1: Permutation Test on LOO Section Classification Accuracy

Author: OpenAI GPT-5.5
Seed: 42

PURPOSE
=======
Test whether the observed leave-one-out (LOO) section-classification
accuracy of the 83-cell register grammar could plausibly arise by
chance under the observed folio distribution and section imbalance.

NULL HYPOTHESIS
===============
The observed LOO classification accuracy is achievable by chance
given:
    - the observed folio-level feature matrix,
    - and the observed section-size distribution.

The permutation null preserves:
    - section label counts,
    - folio feature vectors,
    - feature covariance structure.

The permutation null destroys:
    - linkage between folio feature vectors and section labels.

WHAT THIS SCRIPT DOES TEST
==========================
- Whether the observed classification accuracy exceeds accuracies
  generated by random reassignment of section labels across folios
  while preserving section-size distribution.
- Empirical null distribution via 1,000 permutations.
- Empirical p-value and z-score.

WHAT THIS SCRIPT DOES NOT TEST
==============================
- Semantic interpretation.
- Any claim about decipherment.
- Any causal explanation for classifier performance.
- Any alternative tokenizer or corpus size.

INPUTS
======
Required files in current working directory:
- MASTER_TOKEN_MATRIX.xlsx
- loo_classification_results.csv

Required Excel sheet:
- tokens_atomic

REQUIRED COLUMNS
================
MASTER_TOKEN_MATRIX.xlsx / tokens_atomic:
- folio
- section
- cell_id

loo_classification_results.csv:
- match

FEATURE MATRIX
==============
Constructs a folio × cell count matrix where:
    rows    = folios
    columns = productive register cells
    values  = counts of cell occurrences in folio

Section label for each folio:
    modal(section) across tokens in folio

Only parsed/productive cells are retained:
    - exclude missing cell_id
    - exclude FUNC
    - exclude unparsed values

OUTPUTS
=======
Creates:
    voynich_loo_permutation_v1/

Artifacts:
- null_distribution.csv
- summary.json
- checksums.json
- figures/null_histogram.png

DEPENDENCIES
============
- pandas
- numpy
- scipy
- scikit-learn
- matplotlib
- openpyxl

USAGE
=====
Run locally from directory containing required input files:

    python voynich_loo_permutation_v1.py
"""

import os
import json
import hashlib
import random
from collections import Counter
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import LeaveOneOut
from sklearn.metrics.pairwise import cosine_similarity


# ============================================================
# Constants
# ============================================================

SEED = 42
N_PERMUTATIONS = 1000

random.seed(SEED)
np.random.seed(SEED)

OUTPUT_DIR = "voynich_loo_permutation_v1"
FIG_DIR = os.path.join(OUTPUT_DIR, "figures")


# ============================================================
# Utility Functions
# ============================================================

def sha256_file(path):
    """
    Compute SHA-256 hash of a file.
    """

    sha = hashlib.sha256()

    with open(path, "rb") as f:

        while True:

            chunk = f.read(8192)

            if not chunk:
                break

            sha.update(chunk)

    return sha.hexdigest()


def ensure_dirs():
    """
    Create output directories.
    """

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(FIG_DIR, exist_ok=True)


def detect_column(df, candidates):
    """
    Detect first matching column name from candidate list.
    """

    lower_map = {
        c.lower(): c
        for c in df.columns
    }

    for cand in candidates:

        if cand.lower() in lower_map:
            return lower_map[cand.lower()]

    raise ValueError(
        f"Could not detect required column. "
        f"Tried candidates: {candidates}"
    )


def modal_value(series):
    """
    Return modal value from a series.
    """

    counts = Counter(series.dropna())

    if len(counts) == 0:
        return np.nan

    return counts.most_common(1)[0][0]


# ============================================================
# Initialize
# ============================================================

print("\n====================================================")
print("VOYNICH LOO PERMUTATION TEST V1")
print("====================================================\n")

ensure_dirs()


# ============================================================
# Load Inputs
# ============================================================

INPUT_FILES = [
    "MASTER_TOKEN_MATRIX.xlsx",
    "loo_classification_results.csv"
]

print("[1/8] Loading input files...")

for f in INPUT_FILES:

    if not os.path.exists(f):

        raise FileNotFoundError(
            f"Missing required input file: {f}"
        )

token_df = pd.read_excel(
    "MASTER_TOKEN_MATRIX.xlsx",
    sheet_name="tokens_atomic"
)

loo_df = pd.read_csv(
    "loo_classification_results.csv"
)

print("Loaded:")
print(
    f"  - MASTER_TOKEN_MATRIX.xlsx "
    f"({len(token_df)} rows)"
)

print(
    f"  - loo_classification_results.csv "
    f"({len(loo_df)} rows)"
)


# ============================================================
# Detect Required Columns
# ============================================================

print("\n[2/8] Detecting required columns...")

folio_col = detect_column(
    token_df,
    ["folio"]
)

section_col = detect_column(
    token_df,
    ["section"]
)

cell_col = detect_column(
    token_df,
    ["cell_id"]
)

match_col = detect_column(
    loo_df,
    ["match"]
)

print(f"Detected folio column: {folio_col}")
print(f"Detected section column: {section_col}")
print(f"Detected cell column: {cell_col}")
print(f"Detected match column: {match_col}")


# ============================================================
# Filter Productive Cells
# ============================================================

print("\n[3/8] Filtering productive register cells...")

token_df = token_df.copy()

token_df[cell_col] = (
    token_df[cell_col]
    .astype(str)
    .str.strip()
)

exclude_values = {
    "",
    "nan",
    "NaN",
    "NONE",
    "None",
    "FUNC"
}

token_df = token_df[
    ~token_df[cell_col].isin(exclude_values)
]

print(
    f"Remaining token rows after filtering: "
    f"{len(token_df)}"
)


# ============================================================
# Construct Folio × Cell Matrix
# ============================================================

print("\n[4/8] Constructing folio × cell matrix...")

folio_cell = pd.crosstab(
    token_df[folio_col],
    token_df[cell_col]
)

print(
    f"Folio × cell matrix shape: "
    f"{folio_cell.shape}"
)

n_cells = folio_cell.shape[1]

print(
    f"Detected productive cells: "
    f"{n_cells}"
)


# ============================================================
# Compute Modal Section Labels
# ============================================================

print("\n[5/8] Computing modal section per folio...")

folio_sections = (
    token_df
    .groupby(folio_col)[section_col]
    .agg(modal_value)
)

if folio_sections.isna().any():

    raise RuntimeError(
        "Missing modal section labels detected."
    )

common_folios = (
    folio_cell.index
    .intersection(folio_sections.index)
)

folio_cell = folio_cell.loc[common_folios]
folio_sections = folio_sections.loc[common_folios]

X = folio_cell.values
y = folio_sections.astype(str).values

print(f"Final folio count: {len(common_folios)}")
print(f"Feature matrix shape: {X.shape}")


# ============================================================
# Compute Observed Accuracy
# ============================================================

print("\n[6/8] Computing observed accuracy...")

match_values = pd.to_numeric(
    loo_df[match_col],
    errors="coerce"
)

if match_values.isna().all():

    raise RuntimeError(
        "Match column contains no numeric values."
    )

observed_accuracy = float(
    match_values.mean()
)

print(
    f"Observed accuracy: "
    f"{observed_accuracy:.6f}"
)


# ============================================================
# Define LOO Classifier
# ============================================================

print(
    "\n[7/8] Defining LOO cosine-nearest-centroid "
    "classifier..."
)

loo = LeaveOneOut()


def compute_loo_accuracy(features, labels):
    """
    Leave-one-out nearest-centroid classifier
    using cosine similarity.
    """

    correct = 0
    total = 0

    for train_idx, test_idx in loo.split(features):

        X_train = features[train_idx]
        y_train = labels[train_idx]

        X_test = features[test_idx][0]
        y_test = labels[test_idx][0]

        unique_classes = np.unique(y_train)

        centroids = []

        for cls in unique_classes:

            centroid = X_train[
                y_train == cls
            ].mean(axis=0)

            centroids.append(centroid)

        centroids = np.vstack(centroids)

        sims = cosine_similarity(
            X_test.reshape(1, -1),
            centroids
        )[0]

        pred = unique_classes[
            np.argmax(sims)
        ]

        if pred == y_test:
            correct += 1

        total += 1

    return correct / total


# ============================================================
# Permutation Test
# ============================================================

print("\n[8/8] Running permutation test...")
print(f"Permutations: {N_PERMUTATIONS}")
print("This may take some time.\n")

null_accuracies = []

for i in range(N_PERMUTATIONS):

    shuffled_labels = np.random.permutation(y)

    acc = compute_loo_accuracy(
        X,
        shuffled_labels
    )

    null_accuracies.append(acc)

    if (i + 1) % 50 == 0:

        print(
            f"Completed "
            f"{i + 1}/{N_PERMUTATIONS}"
        )

null_accuracies = np.array(null_accuracies)

null_mean = float(
    np.mean(null_accuracies)
)

null_std = float(
    np.std(null_accuracies)
)

if null_std == 0:
    z_score = float("inf")
else:
    z_score = float(
        (observed_accuracy - null_mean)
        / null_std
    )

empirical_p = (
    np.sum(
        null_accuracies >= observed_accuracy
    ) + 1
) / (N_PERMUTATIONS + 1)

print("\nPermutation test complete.")

print(
    f"Observed accuracy: "
    f"{observed_accuracy:.6f}"
)

print(
    f"Null mean: "
    f"{null_mean:.6f}"
)

print(
    f"Null std: "
    f"{null_std:.6f}"
)

print(
    f"Z-score: "
    f"{z_score:.6f}"
)

print(
    f"Empirical p-value: "
    f"{empirical_p:.6f}"
)


# ============================================================
# Save Null Distribution
# ============================================================

print("\nWriting outputs...")

null_df = pd.DataFrame({
    "permutation": np.arange(
        1,
        N_PERMUTATIONS + 1
    ),
    "accuracy": null_accuracies
})

null_csv_path = os.path.join(
    OUTPUT_DIR,
    "null_distribution.csv"
)

null_df.to_csv(
    null_csv_path,
    index=False
)


# ============================================================
# Plot Histogram
# ============================================================

plt.figure(figsize=(10, 6))

plt.hist(
    null_accuracies,
    bins=30,
    alpha=0.8
)

plt.axvline(
    observed_accuracy,
    linewidth=3,
    linestyle="--",
    label=(
        f"Observed = "
        f"{observed_accuracy:.3f}"
    )
)

plt.xlabel("LOO Accuracy")
plt.ylabel("Frequency")

plt.title(
    "Permutation Null Distribution "
    "of LOO Accuracy"
)

plt.legend()

hist_path = os.path.join(
    FIG_DIR,
    "null_histogram.png"
)

plt.tight_layout()

plt.savefig(
    hist_path,
    dpi=300
)

plt.close()


# ============================================================
# Summary JSON
# ============================================================

summary = {

    "test_name":
        "LOO Permutation Test",

    "version":
        "v1",

    "null_hypothesis": (
        "Observed LOO classification accuracy "
        "is achievable by chance given the "
        "observed folio-level feature matrix "
        "and section-size imbalance."
    ),

    "null_preserves": [
        "section label counts",
        "folio feature vectors",
        "feature covariance structure"
    ],

    "null_destroys": [
        "folio-feature/section linkage"
    ],

    "observed_accuracy":
        observed_accuracy,

    "null_distribution_mean":
        null_mean,

    "null_distribution_std":
        null_std,

    "z_score":
        z_score,

    "empirical_p_value":
        empirical_p,

    "n_permutations":
        N_PERMUTATIONS,

    "seed":
        SEED,

    "n_folios":
        int(X.shape[0]),

    "n_cells":
        int(X.shape[1]),

    "timestamp_utc":
        datetime.now(
            timezone.utc
        ).isoformat(),

    "input_files": {
        f: sha256_file(f)
        for f in INPUT_FILES
    },

    "library_versions": {
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "matplotlib": plt.matplotlib.__version__
    }
}

summary_path = os.path.join(
    OUTPUT_DIR,
    "summary.json"
)

with open(
    summary_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        summary,
        f,
        indent=2
    )


# ============================================================
# Checksums
# ============================================================

artifact_paths = [
    null_csv_path,
    summary_path,
    hist_path
]

checksums = {}

for path in artifact_paths:

    checksums[
        os.path.basename(path)
    ] = sha256_file(path)

checksums_path = os.path.join(
    OUTPUT_DIR,
    "checksums.json"
)

with open(
    checksums_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        checksums,
        f,
        indent=2
    )


# ============================================================
# Complete
# ============================================================

print("\n====================================================")
print("COMPLETE")
print("====================================================")

print(
    f"Output directory: "
    f"{OUTPUT_DIR}"
)

print("Artifacts written:")
print("  - null_distribution.csv")
print("  - summary.json")
print("  - checksums.json")
print("  - figures/null_histogram.png")

print("====================================================\n")